name: StatsCraft
version: 1.1.2
main: tk.snr1s.statscraft.Main
author: snr1s_
commands:
  statscraft:
    usage: /statscraft
    description: Shows stats.
permissions:
  statscraft.use:
    default: op
    description: Permission to use this plugin.